# Data Understanding — HUPA-UCM Diabetes Dataset

## Objective

The goal of this notebook is to understand the structure, quality, and characteristics of the HUPA-UCM Diabetes Dataset before performing cleaning, feature engineering, and advanced analysis.

This notebook focuses on:

- understanding dataset structure
- identifying available variables
- checking data consistency
- validating timestamps
- understanding patient coverage
- performing initial exploratory summaries
- identifying possible data quality issues

A strong data understanding phase helps ensure that future analysis, statistical reasoning, visualizations, and predictive models are reliable and medically meaningful.

# Import Required Libraries

We import libraries required for:

- data manipulation
- visualization
- file handling
- statistical summaries

These libraries form the foundation for the rest of the project.

## Why This Step Is Important

Importing libraries at the beginning keeps the notebook organized and ensures reproducibility.

## Consequence If Skipped

Without properly importing libraries:

- code cells may fail unexpectedly
- visualizations may not render
- preprocessing and analysis workflows become inconsistent

In [1]:
# ================================
# Core Python Libraries
# ================================

import os
import glob

# ================================
# Data Manipulation
# ================================

import pandas as pd
import numpy as np

# ================================
# Visualization Libraries
# ================================

import matplotlib.pyplot as plt
import seaborn as sns

# ================================
# Display Settings
# ================================

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully.")

Libraries imported successfully.

# Universal Visualization Styling

This section defines a universal visualization theme that will automatically apply to all charts throughout the notebook.

The objective is to create:

- professional-looking charts
- consistent visual appearance
- vibrant readable colors
- cleaner storytelling visuals
- presentation-ready outputs

## Why This Step Is Important

Consistent visualization styling improves:

- readability
- professionalism
- insight communication
- dashboard consistency
- stakeholder presentation quality

## Consequence If Skipped

If visualization styling is not standardized:

- charts may look inconsistent
- colors may become repetitive
- presentations may appear unprofessional
- interpretation becomes harder

In [2]:
# ============================================
# Universal Chart Styling Configuration
# ============================================

# Seaborn theme
sns.set_theme(
    style="whitegrid",
    context="notebook"
)

# Vibrant custom palette
custom_palette = [
    "#FF6B6B",  # coral red
    "#4ECDC4",  # teal
    "#556270",  # dark blue-gray
    "#C7F464",  # lime
    "#FFA600",  # orange
    "#8E44AD",  # purple
    "#2ECC71",  # green
    "#E67E22",  # carrot
    "#3498DB",  # blue
    "#E91E63"   # pink
]

sns.set_palette(custom_palette)

# Matplotlib settings
plt.rcParams["figure.figsize"] = (12, 6)
plt.rcParams["axes.titlesize"] = 18
plt.rcParams["axes.labelsize"] = 14
plt.rcParams["xtick.labelsize"] = 11
plt.rcParams["ytick.labelsize"] = 11
plt.rcParams["legend.fontsize"] = 11

print("Universal chart styling applied successfully.")

Universal chart styling applied successfully.

# Define Dataset Location

This step identifies the location of the raw patient CSV files.

The dataset consists of multiple patient-level files, each containing glucose and activity-related measurements.

## Why This Step Is Important

Explicitly defining paths:

- improves reproducibility
- avoids hardcoded file confusion
- makes project structure scalable

## Consequence If Skipped

Without organized path management:

- notebooks become difficult to maintain
- portability becomes poor
- file loading errors increase

In [10]:
os.listdir("../data/raw")

['HUPA-UC Diabetes Dataset']

In [7]:
# ============================================
# Define Dataset Paths
# ============================================

DATA_DIR = "../data/raw/HUPA-UC Diabetes Dataset"

print("Dataset directory defined successfully.")
print(DATA_DIR)

Dataset directory defined successfully.
../data/raw/HUPA-UC Diabetes Dataset

# Inspect Raw Dataset Files

This step checks whether all patient files are available and confirms that the dataset was loaded correctly.

## Why This Step Is Important

This helps verify:

- dataset extraction success
- file naming consistency
- patient file availability

## Consequence If Skipped

If files are missing or corrupted:

- later preprocessing may fail
- patient-level analysis may become incomplete

In [8]:
# ============================================
# List Files in Raw Data Folder
# ============================================

all_files = os.listdir(DATA_DIR)

print("Total files found:", len(all_files))
print()

all_files[:10]

Total files found: 27

['HUPA0001P.csv',
 'HUPA0002P.csv',
 'HUPA0003P.csv',
 'HUPA0004P.csv',
 'HUPA0005P.csv',
 'HUPA0006P.csv',
 'HUPA0007P.csv',
 'HUPA0009P.csv',
 'HUPA0010P.csv',
 'HUPA0011P.csv']

# Load Sample Patient Dataset

Before combining all patient files, we inspect a single patient file to understand:

- available columns
- data types
- time format
- measurement structure

## Why This Step Is Important

Understanding one file first helps validate assumptions before performing large-scale dataset merging.

## Consequence If Skipped

Combining files blindly may introduce:

- inconsistent schemas
- hidden formatting problems
- invalid assumptions

In [9]:
# ============================================
# Load Sample Patient File
# ============================================

sample_file = os.path.join(DATA_DIR, "HUPA0001P.csv")

df_sample = pd.read_csv(sample_file)

print("Sample dataset shape:", df_sample.shape)

Sample dataset shape: (4096, 1)

# Inspect Dataset Structure

We now inspect:

- columns
- data types
- missing values
- memory usage

## Why This Step Is Important

This step provides an initial understanding of:

- numerical variables
- categorical variables
- possible preprocessing requirements

## Consequence If Skipped

Without understanding structure:

- incorrect preprocessing decisions may occur
- analysis logic may become invalid

In [11]:
# ============================================
# Dataset Structure
# ============================================

df_sample.info()

<class 'pandas.DataFrame'>
RangeIndex: 4096 entries, 0 to 4095
Data columns (total 1 columns):
 #   Column                                                                               Non-Null Count  Dtype
---  ------                                                                               --------------  -----
 0   time;glucose;calories;heart_rate;steps;basal_rate;bolus_volume_delivered;carb_input  4096 non-null   str
dtypes: str(1)
memory usage: 376.1 KB

# Preview Dataset

We inspect the first few rows to understand:

- glucose measurements
- timestamps
- activity variables
- insulin variables
- carbohydrate records

## Why This Step Is Important

Visual inspection often reveals issues not visible through summaries alone.

## Consequence If Skipped

Potential formatting or logic issues may remain unnoticed.

In [12]:
# ============================================
# Preview Dataset
# ============================================

df_sample.head()

  time;glucose;calories;heart_rate;steps;basal_rate;bolus_volume_delivered;carb_input
0  2018-06-13T18:40:00;332.0;6.359500050544739;82...
1  2018-06-13T18:45:00;326.0;7.72799998521805;83....
2  2018-06-13T18:50:00;330.0;4.749500036239624;80...
3  2018-06-13T18:55:00;324.0;6.359499931335449;89...
4  2018-06-13T19:00:00;306.0;5.151999890804291;92...

# Statistical Summary

We calculate summary statistics for numerical variables.

This helps identify:

- ranges
- unusual values
- possible outliers
- overall glucose behavior

## Why This Step Is Important

Statistical summaries help establish baseline characteristics of the dataset.

## Consequence If Skipped

Outliers and unusual distributions may remain undetected.

In [13]:
# ============================================
# Statistical Summary
# ============================================

df_sample.describe()

       time;glucose;calories;heart_rate;steps;basal_rate;bolus_volume_delivered;carb_input
count                                                4096
unique                                               4096
top     2018-06-13T18:40:00;332.0;6.359500050544739;82...
freq                                                    1

## Check All CSV Files

In [16]:
# ============================================
# Get All CSV Files Automatically
# ============================================

csv_files = glob.glob(os.path.join(DATA_DIR, "*.csv"))

print("Total CSV files found:", len(csv_files))

csv_files[:5]

Total CSV files found: 26

['../data/raw/HUPA-UC Diabetes Dataset\\HUPA0001P.csv',
 '../data/raw/HUPA-UC Diabetes Dataset\\HUPA0002P.csv',
 '../data/raw/HUPA-UC Diabetes Dataset\\HUPA0003P.csv',
 '../data/raw/HUPA-UC Diabetes Dataset\\HUPA0004P.csv',
 '../data/raw/HUPA-UC Diabetes Dataset\\HUPA0005P.csv']

In [17]:
# Load first patient file dynamically

sample_file = csv_files[0]

df_sample = pd.read_csv(sample_file)

print("Loaded file:", sample_file)
print("Shape:", df_sample.shape)

Loaded file: ../data/raw/HUPA-UC Diabetes Dataset\HUPA0001P.csv
Shape: (4096, 1)

## Identify All Patient CSV Files

Now that the dataset path is correct, we identify all patient-level CSV files.

### Why This Step Is Important

The dataset contains multiple patient files. Before combining them, we need to confirm how many patient files exist and make sure we do not accidentally include demographic or unrelated files.

### Consequence If Skipped

If we combine files blindly, we may accidentally include non-patient files, create wrong columns, or corrupt the analysis dataset.

In [18]:
# Get all CSV files in the dataset folder
csv_files = glob.glob(os.path.join(DATA_DIR, "*.csv"))

# Keep only patient files that start with HUPA and end with P.csv
patient_files = [
    file for file in csv_files
    if os.path.basename(file).startswith("HUPA") and os.path.basename(file).endswith("P.csv")
]

print("Total CSV files found:", len(csv_files))
print("Total patient files found:", len(patient_files))

patient_files[:5]

Total CSV files found: 26
Total patient files found: 25

['../data/raw/HUPA-UC Diabetes Dataset\\HUPA0001P.csv',
 '../data/raw/HUPA-UC Diabetes Dataset\\HUPA0002P.csv',
 '../data/raw/HUPA-UC Diabetes Dataset\\HUPA0003P.csv',
 '../data/raw/HUPA-UC Diabetes Dataset\\HUPA0004P.csv',
 '../data/raw/HUPA-UC Diabetes Dataset\\HUPA0005P.csv']

## Validate Column Consistency Across Patient Files

Before combining files, we check whether all patient files have the same columns.

### Why This Step Is Important

Combining datasets only makes sense if the files have a consistent structure. Since each file represents a patient, column consistency ensures that glucose, insulin, activity, and food variables are aligned correctly.

### Consequence If Skipped

If one file has missing or extra columns, the combined dataset may contain incorrect missing values or misleading analysis results.

In [19]:
# Check column consistency across all patient files
column_check = {}

for file in patient_files:
    temp_df = pd.read_csv(file, nrows=5)
    column_check[os.path.basename(file)] = list(temp_df.columns)

# Convert to DataFrame for easier review
column_check_df = pd.DataFrame.from_dict(column_check, orient="index")

column_check_df.head()

                                                               0
HUPA0001P.csv  time;glucose;calories;heart_rate;steps;basal_r...
HUPA0002P.csv  time;glucose;calories;heart_rate;steps;basal_r...
HUPA0003P.csv  time;glucose;calories;heart_rate;steps;basal_r...
HUPA0004P.csv  time;glucose;calories;heart_rate;steps;basal_r...
HUPA0005P.csv  time;glucose;calories;heart_rate;steps;basal_r...

In [20]:
# Count unique column structures
unique_column_sets = set(tuple(cols) for cols in column_check.values())

print("Number of unique column structures:", len(unique_column_sets))

for cols in unique_column_sets:
    print(cols)

Number of unique column structures: 1
('time;glucose;calories;heart_rate;steps;basal_rate;bolus_volume_delivered;carb_input',)

## Combine Patient Files

Each patient file contains time-series health measurements. We combine all patient files into one dataset and create a patient_id column from the file name.

### Why This Step Is Important

A combined dataset allows us to perform population-level and patient-level analysis.

This supports questions such as:

- Which patients have higher average glucose?
- How does glucose vary across time?
- Are insulin, activity, and carbohydrate intake related to glucose?
- Are some patients more likely to experience high or low glucose?

### Consequence If Skipped

Without combining files, we would only analyze one patient at a time and miss broader patterns across the full dataset.

In [21]:
# Combine all patient CSV files into one DataFrame
combined_data = []

for file in patient_files:
    temp_df = pd.read_csv(file)
    
    # Extract patient ID from file name
    patient_id = os.path.basename(file).replace(".csv", "")
    
    # Add patient ID column
    temp_df["patient_id"] = patient_id
    
    # Append to list
    combined_data.append(temp_df)

df = pd.concat(combined_data, ignore_index=True)

print("Combined dataset shape:", df.shape)
df.head()

Combined dataset shape: (309392, 2)

,time;glucose;calories;heart_rate;steps;basal_rate;bolus_volume_delivered;carb_input,patient_id
0,2018-06-13T18:40:00;332.0;6.359500050544739;82...,HUPA0001P
1,2018-06-13T18:45:00;326.0;7.72799998521805;83....,HUPA0001P
2,2018-06-13T18:50:00;330.0;4.749500036239624;80...,HUPA0001P
3,2018-06-13T18:55:00;324.0;6.359499931335449;89...,HUPA0001P
4,2018-06-13T19:00:00;306.0;5.151999890804291;92...,HUPA0001P

## Inspect Combined Dataset

After combining patient files, we inspect the complete dataset.

### Why This Step Is Important

This confirms that the merge worked correctly and that patient_id was added successfully.

### Consequence If Skipped

Errors during merging may go unnoticed and affect every future notebook.

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 309392 entries, 0 to 309391
Data columns (total 2 columns):
 #   Column                                                                               Non-Null Count   Dtype
---  ------                                                                               --------------   -----
 0   time;glucose;calories;heart_rate;steps;basal_rate;bolus_volume_delivered;carb_input  309392 non-null  str
 1   patient_id                                                                           309392 non-null  str
dtypes: str(2)
memory usage: 32.1 MB

In [23]:
df.head()

,time;glucose;calories;heart_rate;steps;basal_rate;bolus_volume_delivered;carb_input,patient_id
0,2018-06-13T18:40:00;332.0;6.359500050544739;82...,HUPA0001P
1,2018-06-13T18:45:00;326.0;7.72799998521805;83....,HUPA0001P
2,2018-06-13T18:50:00;330.0;4.749500036239624;80...,HUPA0001P
3,2018-06-13T18:55:00;324.0;6.359499931335449;89...,HUPA0001P
4,2018-06-13T19:00:00;306.0;5.151999890804291;92...,HUPA0001P

In [24]:
df.tail()

,time;glucose;calories;heart_rate;steps;basal_rate;bolus_volume_delivered;carb_input,patient_id
309387,2022-05-18T11:55:00;109.33333333333333;10.7927...,HUPA0028P
309388,2022-05-18T12:00:00;114.0;9.803459882736206;10...,HUPA0028P
309389,2022-05-18T12:05:00;118.66666666666667;5.66621...,HUPA0028P
309390,2022-05-18T12:10:00;123.33333333333334;5.57627...,HUPA0028P
309391,2022-05-18T12:15:00;128.0;5.576279997825623;99...,HUPA0028P

# Check Patient Count

The dataset description says the data was collected from 25 people with Type 1 Diabetes. We verify that the combined dataset includes the expected number of patients.

### Why This Step Is Important

Patient count validation confirms dataset completeness.

### Consequence If Skipped

If patients are missing, conclusions may be incomplete or biased.

In [25]:
patient_count = df["patient_id"].nunique()

print("Number of unique patients:", patient_count)
print("Patient IDs:")
print(sorted(df["patient_id"].unique()))

Number of unique patients: 25
Patient IDs:
['HUPA0001P', 'HUPA0002P', 'HUPA0003P', 'HUPA0004P', 'HUPA0005P', 'HUPA0006P', 'HUPA0007P', 'HUPA0009P', 'HUPA0010P', 'HUPA0011P', 'HUPA0014P', 'HUPA0015P', 'HUPA0016P', 'HUPA0017P', 'HUPA0018P', 'HUPA0019P', 'HUPA0020P', 'HUPA0021P', 'HUPA0022P', 'HUPA0023P', 'HUPA0024P', 'HUPA0025P', 'HUPA0026P', 'HUPA0027P', 'HUPA0028P']

## Save Combined Raw Dataset

We save the combined dataset into the processed folder.

This file is not fully cleaned yet. It is a combined version of the raw patient files and will be used as input for the cleaning notebook.

### Why This Step Is Important

Saving an intermediate dataset improves workflow organization and prevents repeated loading and merging.

### Consequence If Skipped

Every future notebook would need to repeat the combining process, increasing runtime and chances of mistakes.

In [26]:
# Save combined dataset
output_path = "../data/processed/combined_raw_patient_data.csv"

df.to_csv(output_path, index=False)

print("Combined raw dataset saved successfully.")
print("File path:", output_path)

Combined raw dataset saved successfully.
File path: ../data/processed/combined_raw_patient_data.csv